# Generated by Django 3.2a1 on 2021-02-14 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210214_1512'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SomeModel',
        ),
    ]
