# Generated by Django 3.2a1 on 2021-02-14 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_delete_somemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_value', models.IntegerField(blank=True, choices=[(0, 'Нет скидки'), (5, '5%'), (10, '10%'), (15, '15%'), (20, '20%'), (25, '25%'), (30, '30%'), (35, '35%'), (40, '40%'), (45, '45%'), (50, '50%')], default=0, verbose_name='Скидка в процентах')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='discount_value',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='products.discount', verbose_name='Скидка в процентах'),
        ),
    ]
