# Generated by Django 3.2a1 on 2021-02-14 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_discount_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_value',
        ),
    ]
