# Generated by Django 3.2a1 on 2021-02-14 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_discount_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.discount', verbose_name='Скидка в процентах'),
        ),
    ]
