# Generated by Django 3.2a1 on 2021-02-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_discount_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.IntegerField(default=0, verbose_name='Цена со скидкой'),
        ),
    ]
