# Generated by Django 3.2a1 on 2021-02-14 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_discount_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'Скидка', 'verbose_name_plural': 'Скидки'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
