# Generated by Django 3.2a1 on 2021-02-14 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20210214_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_value',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='products.discount', verbose_name='Скидка в процентах'),
        ),
    ]
