# Generated by Django 3.2a1 on 2021-02-14 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_discount_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_value',
            field=models.IntegerField(choices=[(0, 'Нет скидки'), (5, '5%'), (10, '10%'), (15, '15%'), (20, '20%'), (25, '25%'), (30, '30%'), (35, '35%'), (40, '40%'), (45, '45%'), (50, '50%')], default=0, verbose_name='Скидка в процентах'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.IntegerField(blank=True, default=0, verbose_name='Цена со скидкой'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_value',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.discount', verbose_name='Скидка в процентах'),
        ),
    ]
