# Generated by Django 3.2a1 on 2021-02-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_product_discount_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_value',
            field=models.ForeignKey(blank=True, default=None, on_delete=models.SET(None), to='products.discount', verbose_name='Скидка в процентах'),
        ),
    ]
